### ISSUE TITLE
[Bug]: In firefox, scrollbar issue

### ISSUE THREAD

**Issue by liulo6** [ceolter/ag-grid#10125]
### Link to reproducible scenario

https://www.ag-grid.com/example/

### Describe the bug

Steps to reproduce 
1.  AG GRID 33.1.1, Just in firefox

![Image](https://github.com/user-attachments/assets/756db21e-3364-41f2-b523-b8061d4e2e5f)

2.  In demo grid, Roll the scrollbar to the middle of the page

![Image](https://github.com/user-attachments/assets/53957c36-7509-4457-97fb-9233d9e6224c)

2.  Refresh the page

Actual behaviour
The scroll bar does not return to the top of the grid, and the grid is empty.
When I scroll the mouse again, the data will appear

![Image](https://github.com/user-attachments/assets/58272605-1780-4302-b6d1-2fd7ca8bd666)

Expected behaviour
The scrollbar should go back to the top and the grid data is displayed properly

More information

### Version

33.1.1

### Does the issue occur for a specific framework only?

All languages

### Is the issue only observable on a specific browser?

Firefox

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-14550**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can follow the status of this item on the product pipeline page:
https://ag-grid.com/pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by JamesPScottPharm3r** [comment]
@AG-Zoheil - Was this ever fixed?  Its marked as completed, but I can still see this behavior in v34 and 35...  I do see it working on your example site so perhaps there is a flag?  Can you comment further?

**Comment by AG-Zoheil** [comment]
Hi,

**AG-14550** is scheduled for release in `v35.2.0`.

Kind regards,
