### ISSUE TITLE
[Bug]: Horizontal scrollbar positioned incorrectly when applying initialState

### ISSUE THREAD

**Issue by gretencord** [ceolter/ag-grid#10334]
### Link to reproducible scenario

https://codesandbox.io/p/sandbox/grid-state-jyhhdl

### Describe the bug

**Steps to reproduce** 
1. Size the browser window so horizontal scrolling in the grid is necessary.
2. Horizontally scroll the grid to the right until the "Country" column is the leftmost visible.
3. Click the "Recreate Grid with Current State" button.

**Actual behaviour**
"Country" is still the leftmost column but the horizontal scrollbar has moved all the way to the left.

**Expected behaviour**
The horizontal scrollbar should be positioned off to the right where it was prior to clicking "Recreate..."

**More information**
The CodeSandbox sample is an unaltered fork of [this example](https://www.ag-grid.com/react-data-grid/grid-state/#saving-and-restoring-state) from the documentation. _Note: I cannot explain it but the issue is **not** reproducible if Chrome Dev Tools is open._

### Version

33.2.3

### Does the issue occur for a specific framework only?

All languages

### Is the issue only observable on a specific browser?

All browsers

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-14719**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can follow the status of this item on the product pipeline page:
https://ag-grid.com/pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by kozmit** [comment]
This bugs still seems to exist in version 34.0.2. The issue AG-14719 did not resolve the described problem and for me it still shows when loading an initial state.
