### ISSUE TITLE
[Bug]: Rows are not rendered properly when a filter is applied (in Firefox)

### ISSUE THREAD

**Issue by radeoliv** [ceolter/ag-grid#10598]
### Link to reproducible scenario

https://www.ag-grid.com/example/

### Describe the bug

Steps to reproduce
This seems to only happen in Firefox. Can be reproduced using the example/demos ag-grid page.
1. Scroll to the middle of the grid.
2. Apply a filter to any column.
3. Note that sometimes not all rows are rendered after the filter is applied.

Actual behaviour
Several rows are not rendered. In the following image, only the last row shows up. All rows appear if you interact with the grid (scroll, sort, etc.).

![Image](https://github.com/user-attachments/assets/21142ce8-8b0c-424c-ad91-4cbe1be07781)

Expected behaviour
All rows should be rendered properly after a filter is applied.

More information
I am only able to reproduce this in Firefox (currently using version 136.0 on ubuntu).

### Version

Verified that this happens with versions 33.2.1 and 33.3.0 (react). Unsure about other versions/frameworks.

### Does the issue occur for a specific framework only?

React

### Is the issue only observable on a specific browser?

Firefox

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-14985**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can follow the status of this item on the product pipeline page:
https://ag-grid.com/pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by sabahang** [comment]
@radeoliv we cannot reproduce this in our latest version. Can you please confirm?

**Comment by radeoliv** [comment]
> [@radeoliv](https://github.com/radeoliv) we cannot reproduce this in our latest version. Can you please confirm?

Still reproducible in my own application using v34.2.0 and on the ag-grid demo page:

<img width="1891" height="2087" alt="Image" src="https://github.com/user-attachments/assets/360c3efc-d983-473a-a228-cf45ff383a6d" />

**Comment by Higgy831** [comment]
We are experiencing the same issue in our results table.

We display database query results in an AG Grid table. When the query changes and the new response contains significantly fewer rows than the previous result set, the behavior described by radeoliv also occurs in our case.

The rows are not rendered correctly until the user interacts with the table (e.g., sorting a column or scrolling), which triggers a re-render.

Calling api.redrawRows() also resolves the issue, but it resets user interactions such as row selections, which is not acceptable for our use case.

It appears that this issue only occurs in Firefox. In Edge, the table behaves as expected.

**Comment by byronbaz** [comment]
We are also experiencing this issue.  It is even reproducible on the ag-grid example page.

**This bug does not reproduce on Chrome.**

To reproduce:

With 100 rows of data:
1) Open a current version of Firefox (was able to reproduce on Windows and Linux)
2) visit the ag-grid performance example page: https://www.ag-grid.com/example/
3) Hide the columns side-drawer so you can access the scrollbar for the table
4) Scroll to the bottom
5) Click the scrollbar at the top.  Slider bar returns to the top.

**Expected**: view of top rows of data
**Actual**: Blank

With 50,000 rows:
Same first three steps
4) Change the dropdown to change the data size to 50,000 rows
5) Slowly pull the scrollbar downwards.  It will flash.  You will find that in certain situations, it is fairly easy to end up with a blank window.

**Expected**: Smooth scrolling of data
**Actual**: Flashing and showing blank window

Edit: looks like there may be activity on this topic here: https://github.com/ag-grid/ag-grid/issues/13141
