### ISSUE TITLE
[Bug]: Rows are not rendered properly when clicking on the scrollbar track instead of scrolling (in Firefox)

### ISSUE THREAD

**Issue by radeoliv** [ceolter/ag-grid#10599]
### Link to reproducible scenario

https://www.ag-grid.com/example/

### Describe the bug

I'm unsure if this is related to https://github.com/ag-grid/ag-grid/issues/10598 but I can only reproduce this in Firefox.

Steps to reproduce 
1. Navigate the rows in a grid by clicking on the scrollbar track instead of using the scroll wheel or by dragging the scrollbar thumb.
2.  See that some (or all) rows that should be visible are not rendered properly. 

Actual behaviour
Rows are not rendered.

![Image](https://github.com/user-attachments/assets/8b56c35d-b652-4068-881a-25cf5fd4fa68)

Expected behaviour
All rows should be rendered properly.

More information
I am only able to reproduce this in Firefox (currently using version 136.0 on ubuntu).

### Version

Verified that this happens with versions 33.2.1 and 33.3.0 (react). Unsure about other versions/frameworks.

### Does the issue occur for a specific framework only?

React

### Is the issue only observable on a specific browser?

Firefox

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-14987**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can follow the status of this item on the product pipeline page:
https://ag-grid.com/pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by sabahang** [comment]
Hi @radeoliv we are unable to reproduce this in our latest versions. Can you confirm please?

**Comment by radeoliv** [comment]
> Hi [@radeoliv](https://github.com/radeoliv) we are unable to reproduce this in our latest versions. Can you confirm please?

I can still reproduce this behavior in the grids throughout the official AG Grid page and in my application using v34.2.0.
