### ISSUE TITLE
Pinning columns right: Header does not align with content when scrolling

### ISSUE THREAD

**Issue by jstreussnig** [ceolter/ag-grid#1220]
I encountered the following layout problem **in Chrome and Edge**, when pinning one or more columns to the right:

![unbenannt](https://cloud.githubusercontent.com/assets/13204117/19676795/78a95e0c-9a96-11e6-918d-201aadad41a2.png)

As you can see the **header is not aligned with the content**, since the scrollbar in the content section moves its columns to the left. 

This problem occures when you have columns pinned to the right and scrollbars in the grid. Since the grid header doesn't have scrollbars, but the content does, it's missing a margin-right of about 18px (depends on the browsers scroll bar size) to be aligned with the content.

This can be quick fixed by adding the following css rule and replacing [scrollbarWidth] with the correct  or estimated value.

`.ag-pinned-right-header {
margin-right: [scrollbarWidth]px
}`

Since this seems to be a bug, I wanted to let you know. I do hope this can be fixed in upcoming versions.

**Comment by ceolter** [comment]
noted. will look into it. thanks for raising.

**Comment by ceolter** [comment]
ps we have known about this for a while, but very few people using right pinning and it's not a huge issue, so we are slow to invest much time in it.

**Comment by andrea-vega** [comment]
+1 for this issue

**Comment by Piccirello** [comment]
+1

**Comment by JoeQueR** [comment]
+1 for this issue

**Comment by Grilly** [comment]
We have a right pinned column and experience the same issue (ag-grid v6.4.2).

**Comment by olragon** [comment]
@ceolter It's happening in documentation too. If you don't have enough resources to fix this right now, please add it's to "Known issues list" somewhere and instruct some temporary solutions.

Right pinning is useful in many place in enterprise applications, eg: display total value of row, row operation buttons (delete row, add row below, edit row ...).

Chrome Version 54.0.2840.59 (64-bit)
https://www.ag-grid.com/javascript-grid-pinning/

![Uploading Selection_044.png…](ag-grid right pinned bug in documentation)

Thank you for your great work <3

**Comment by ceolter** [comment]
i've pushed it up on my list of items, should get to it soon.

**Comment by ceolter** [comment]
this is now fixed. will be in next release (we plan on mid next week).

**Comment by Rebaiahmed** [comment]
Hey I'm using the pinned property and still have same issue with Ag-grid version 29

**Comment by matt-fischer** [comment]
Having the same issue with ag-grid version 30.2.0.

**Comment by victix3** [comment]
Hi ! I'm using the version 30.2.0 so i still have the issue. The project i'm on is using Angular 13 so i cant upgrade to V31. Is there a fix that will be deployed for the latest stable version  for Angular 13 or am i doomed ? 
thanks for your help !

**Comment by AG-Zoheil** [comment]
Hi @victix3,

thank you for your comment. As Angular 13 is only supported up until v30 of the grid you would need to upgrade to Angular >14 when possible to be able to upgrade AG Grid too.

Alternatively, if upgrading Angular isn't an option, you could downgrade your grid to 30.1.0 as I believe this regression only occurs in 30.2.0.

**Comment by victix3** [comment]
Thank you for your answer, i will try the downgrade then (yes it hurts not being able to upgrade to newer versions of angular but you know, company stuff..)

**Comment by AG-Zoheil** [comment]
Hi @harshgoyal7065,

The issue was fixed in `v31` - this is our latest demo https://ag-grid.com/example/.

Are you able to reproduce the issue on there?

Thanks!
