### ISSUE TITLE
sizeColumnsToFit breaks if multiple ag-grids exist on different tabs

### ISSUE THREAD

**Issue by h3adache** [ceolter/ag-grid#1293]
An example of this is when you have 3 tabs. Calling `sizeColumnsToFit` would sometimes return an error that the grid is coming back with zero width.
That is because it calls a function: getWidthForSizeColsToFit which uses an ebody that is set to be a global selector for `.ag-body`. This wouldn't work if you have multiple grids hidden by tabs as you see from the below console code.

```
document.querySelectorAll(".ag-body").forEach((x) => console.log(x.clientWidth))
0
1678
0
```

This is only tested in chrome but it seems that it's either a bug or a there's missing documentation about how to use ag-grid within multiple tabs? (using bootstrap tabs atm).

**Comment by ceolter** [comment]
i searched the code for '.ag-body' and couldn't find.

where are you referring to?

**Comment by h3adache** [comment]
Hi @ceolter it's here https://github.com/ceolter/ag-grid/blob/52d63fa6e8f698f630183bcf96a6ae5cd014344b/dist/lib/gridPanel/gridPanel.js#L783

**Comment by h3adache** [comment]
Sorry to be clear the bug isn't that it uses .ag-body. It's just that the .ag-bodies that have 0 clientWidth have 0 width because they are hidden under tabs that aren't visible at the time.
Calling gridOptions.api.sizeColumnsToFit() seems to call sizeColumnsToFit for all grids that were defined (I've only verified this through the debugger) not just the grid that the gridOptions belongs to.

I can try to setup a simple bootstrap tabs example with this behavior if needed.

**Comment by ceolter** [comment]
```.ag-bodies that have 0 clientWidth have 0 width because they are hidden under tabs``` -> agreed, but nothing i can do here, if grid not visible, then no way for it to know how to spread the columns. however i don't think this is your problem, the problem is....

```Calling gridOptions.api.sizeColumnsToFit() seems to call sizeColumnsToFit for all grids that were defined``` that should definitely no happen. something wrong with your setup! the gridOptions.api as a reference to ONE gridPanel object, and calls sizeColumnsToFit() on that. if you provide a plunker I can take a look? otherwise you can try debugging through it, see what is happening?

my guess is you have somehow confusing references to the gridOptions, or somehow getting the grids mixed up.

**Comment by ceolter** [comment]
no feedback, closing.

**Comment by h3adache** [comment]
Sorry I haven't had time to debug and figure it out. I switched to using a single ag-grid and dynamically changing the columns/report data rather than trying to separate the grids per tab.

**Comment by sukhminderparmar** [comment]
Hi,
Apologies for commenting in the closed issue.
I am facing the same problem.
I have multiple tabs on my Angular page and each tab has an Ag Grid.
So, the tabs that are not visible do not get the sizeColumnsTofit() functionality and I get the following warning:
tried to call sizeColumnsToFit() but the grid is coming back with zero width, maybe the grid is not visible yet on the screen?
I want grids in all the tabs to span across the width of the page.
Please let me know about this.
Thanks.

**Comment by sukhminderparmar** [comment]
Hi, 

Resolved it.

On the selection of a tab, passed the tab id to the child component containing the tab, and detect ngOnChanges in Angular, executed setTimeout with sizeColumnsToFit()

In this way, whenever a new tab is selected, sizeColumnsToFit() will be called after (say) 300ms and the width of the columns will span across the available width.
Any other more efficient way?

Thanks!!

**Comment by ab320012** [comment]
I am having a similar issue because I call sizeColumnsToFit on all grids based on resize. The grids that are hidden throw an error. Will you accept a PR that exposes a method that returns the grid Width from api. ie getWidthForSizeColsToFit()  which sizeColumnsToFit uses internally. Basically I want to do the following

```javascript
onGridReady(params) {
  window.resize(() =>
    // if there is already a call to get the grd width on api object let me know...i couldn't find one
    if (params.api.getWidthForSizeColsToFit()) params.api.sizeColumnsToFit()
  )
}
```

**Comment by akashhnag** [comment]
have we come to any solution to this problem?

**Comment by angelayanpan** [comment]
@ahmadkhoja  Can you explain your work around?  And are people just getting the warning? my grid that's in the second tab is not being "sizedToFit"

**Comment by hugotorres** [comment]
I´m still having the same issue, I am using to grids on two tabs, andim trying to populate the secong rid with rows selected from the first grid so when the user clicks on the second tab, the corresponding grid should display only rows selected on the first tab, and that is working but the row height and width are no being properly reset.

**Comment by rune007** [comment]
Anybody has a working solution to this problem?

**Comment by rune007** [comment]
Getting the warning below when resizing ag-Grid (change size of browser window) and switch between two tabs:

"ag-Grid: tried to call sizeColumnsToFit() but the grid is coming back with zero width, maybe the grid is not visible yet on the screen?"

I have reproduced the situation in a Stackblitz:

[https://angular-jpmxjy.stackblitz.io/](https://angular-jpmxjy.stackblitz.io/)

Here is the composition of the test app: 
- PrimeNG p-tabMenu at the component: header.component 
- ag-Grid at the componenents: delleverancer.component and leverancer.component.

You will see the warning error in chrome dev tools, 
when you resize the grid and switch between tabMenu 'Leverancer' and 'Delleverancer'.

You can see the code here:

[https://stackblitz.com/edit/angular-jpmxjy](https://stackblitz.com/edit/angular-jpmxjy)

How do we remove this unwanted warning error?

**Comment by abu2sid** [comment]
> @ceolter I am having a similar issue because I call sizeColumnsToFit on all grids based on resize. The grids that are hidden throw an error. Will you accept a PR that exposes a method that returns the grid Width from api. ie getWidthForSizeColsToFit() which sizeColumnsToFit uses internally. Basically I want to do the following to avoid the message in console
> 
> ```js
> onGridReady(params) {
>   window.resize(() =>
>     // if there is already a call to get the grd width on api object let me know...i couldn't find one
>     params.api.getWidthForSizeColsToFit() && params.api.sizeColumnsToFit()
>   )
> }
> ```

Hi, Did you find any solution? on were able to solve the issue?

**Comment by rune007** [comment]
I have come across a solution to above problem:
https://stackoverflow.com/questions/54038024/warning-grid-zero-width-when-using-ag-grids-sizecolumnstofit-on-two-separat

**Comment by petemahoney** [comment]
I have worked on getting around this warning message in the console all morning - here's a screenshot of what I'm deciding to live with:
![2019-02-01_12-48-54](https://user-images.githubusercontent.com/5629826/52146084-ff440400-261f-11e9-9511-221860ee5232.jpg)
My app functions fine - just wish there was a way to avoid this warning.  I liked the idea posted above by @ab320012 or something like that.  The other workarounds proposed are way to complex for my app that has several tabs with grids that all need to load at once - can't wait until the user clicks on the tab.

**Comment by gportela85** [comment]
@petemahoney Usually this is an indication of a listener that wasn't destroyed properly or on some apps (React mostly), a call to sizeColumnsToFit() when the window containing the Grid gets hidden due to state change.
But every time I had this warning show up on my screen, it saved me a lot of headache later trying to find memory leaks.

**Comment by marcelogarbin** [comment]
> > @ceolter I am having a similar issue because I call sizeColumnsToFit on all grids based on resize. The grids that are hidden throw an error. Will you accept a PR that exposes a method that returns the grid Width from api. ie getWidthForSizeColsToFit() which sizeColumnsToFit uses internally. Basically I want to do the following to avoid the message in console
> > ```js
> > onGridReady(params) {
> >   window.resize(() =>
> >     // if there is already a call to get the grd width on api object let me know...i couldn't find one
> >     params.api.getWidthForSizeColsToFit() && params.api.sizeColumnsToFit()
> >   )
> > }
> > ```
> 
> Hi, Did you find any solution? on were able to solve the issue?

I tried to use it, but it returns this error:
![image](https://user-images.githubusercontent.com/9335588/57202879-d7e33700-6f80-11e9-9e1b-de325391e5b0.png)

I am using VueJS with Element.io tabs. I'm using 2 tabs, each tab has an ag-grid

**Comment by hinsenchan** [comment]
Potential solution with minor visual flash: 

Try invoking resize code in onFirstDataRendered instead of onGridReady
https://quabr.com/61666755/ag-grid-tried-to-call-sizecolumnstofit-but-the-grid-is-coming-back-with-zero

**Comment by KevinCallagher** [comment]
I guess the reason is that the second grid is not visible yet on the screen because the second tab is not clicked. A workaround:

Remove that from the second grid's options

        onGridReady: function (params) {
            params.api.sizeColumnsToFit();
        },

Add this to your code:

    var secondGridSized = false;

    $('#navigation li a').click(function() {
        if (!secondGridSized) {
            if ($(this).attr('href') === '#files') {
                if (!secondGridSized) {
                    gridOptions1.api.sizeColumnsToFit();
                    secondGridSized = true;
                }
            }
        }
    });

Change files with whatever your tab pane id is.

    <ul class="nav nav-tabs" role="tablist" id="navigation">
    </ul>
    <div class="tab-content">
        <div class="tab-pane active" id="meetingDetails" role="tabpanel">
        </div>
        <div class="tab-pane" id="files" role="tabpanel">
        </div>
    </div>

**Comment by maligautam** [comment]
The simplest solution i found to load multiple Ag grids inside the tabs is to add the `h-full` class to the tabpanel or parent container 
```
.h-full {
    height:'100%'
}
```
