### ISSUE TITLE
wrong pagination page count when using filters

### ISSUE THREAD

**Issue by valfis86** [ceolter/ag-grid#1552]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Please see plunker: https://plnkr.co/edit/gVUxaEYZggKQthoS7Xex
When using a filter to display only a single row the total page count displayed is wrong. Please follow these steps using the plunker example.

Filter the column "Number" to select only the row number 2. => "Page 1 of 3"
Use the same filter to get the rows with the number 22 => "Page 1 of 1"
Use the filter to get the rows with the number 2 again => "Page 1 of 0"

**Expected behavior**

If only one row matches the displayed text should be "Page 1 of 1".
If no row matches the text "Page 1 of 0" (or maybe "Page 0 of 0"?) should be displayed.

**Minimal reproduction of the problem with instructions**
Please see plunker: https://plnkr.co/edit/gVUxaEYZggKQthoS7Xex

**What is the motivation / use case for changing the behavior?**
Filtering + paging

**Please tell us about your environment:**

* **ag-Grid version:** X.X.X
current

* **Browser:**

"Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0"
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
"Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; rv:11.0) like Gecko"

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES5

**Comment by seanlandsman** [comment]
Hi

At the moment if you're using client side pagination and filtering then the filtering only takes place for the current page, not the entire dataset, so what you're seeing is what is expected.

In our next release we'll support full client side filtering of paginated data which should give you the results you're after.

thanks

**Comment by valfis86** [comment]
Hey, 

I implemented a custom datasource to filter the entire dataset not only the current page. This works as expected. But I don't get your point that the calculation of the total page count works as expected. As far as I unterstand the second parameter of the successCallback in the getRows Method of a datasource is used for the calculation of the total page count. In the example above I use the the same filter with the same filter value twice. Therefore the lastRow parameter has the same value. So why do I get two different total page counts?

Any ideas how to implement my needs with the current version of ag-grid? When will the next version be released?

thanks + kind regards

**Comment by seanlandsman** [comment]
Hi

The next version should be released this week - I'd wait and see if this solves your problem. If it doesnt then open a new issue and we can investigate further

The next version is designed for the scenario you're trying to implement

**Comment by valfis86** [comment]
Cool, thanks a lot. I hope the examples will also be updated.

**Comment by nitoloz** [comment]
Hi!
Thank you for an amazing library. I'm using ag-grid 13.3.1 and unfortunately I still have issue with pagination when using client side filtering.
When I filter out the data pagination control shows 'Page 1 of 0' which is a bit odd. Do you plan to fix this in a future releases or this isn't considered as a bug?
![image](https://user-images.githubusercontent.com/7154361/34104830-57bb6df6-e3f2-11e7-956e-34243ef037d4.png)

**Comment by nitoloz** [comment]
Hi everyone!
Just updated the aggrid to 16.0.0 from 13.1.1 and the issue seems to be fixed.
Thank you!
