### ISSUE TITLE
Crash when trying to change the sortModel before setting the datasource (infinite scroll mode)

### ISSUE THREAD

**Issue by Wykks** [ceolter/ag-grid#793]
This fix : https://github.com/ceolter/ag-grid/commit/42b60a3477b6e097042ee7f8a7d7edf79737bfc3
Needs to be applied to virtualPageRowController as well.

Reproduced here : http://plnkr.co/edit/uo1O4GjDbZyFl1YqLPTw?p=preview
(see line 72 in index.html)

`TypeError: Cannot read property 'rowCount' of undefined`

**Comment by gerardqueralt** [comment]
Hi,
The source-code in [github is fixed](https://github.com/ceolter/ag-grid/blob/master/src/ts/rowControllers/virtualPageRowController.ts#L100). But the distributed code (both release, 4.0.4 and 4.0.5) the [fix is missing](https://github.com/ceolter/ag-grid/blob/master/dist/lib/rowControllers/virtualPageRowController.js#L70) .

**Comment by ceolter** [comment]
@gerardqueralt that's probably because i haven't done a release. this is not a critical bug reported by any paying clients, so will be in the next natural release.

**Comment by gerardqueralt** [comment]
@ceolter I was confused after read the release notes of version 4.0.4: 

> [setting sort before datasource on pagination caused error"](https://github.com/ceolter/ag-grid/releases/tag/4.0.4).

 Then, I thought you include this fix in the release 4.0.4.

**Comment by ceolter** [comment]
there are two things that use datasource and had this bug:
pagination (with paging panel) -> got it fixed
virtual pagination -> not fixed
