### ISSUE TITLE
[Vue] Class instances in RowData converted to raw js object

### ISSUE THREAD

**Issue by mmeisso** [ceolter/ag-grid#9574]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**

Plunker : https://plnkr.co/edit/llltfIkCrKHxJ6te?open=main.ts

**Current behavior**

If we pass a class instance to rowData, we get back raw objects.

**Expected behavior**

If we pass a class instance to RowData, we get a class instance back. I shouldn't need to pass by the store again to retrieve my class instance.

**Please tell us about your environment:**

Not relevant

**AG Grid version:** vue 33.X.X

* **Browser:** Any

* **Language:** all

** More information

I guess it's due to 
```ts
export function deepToRaw<T extends Record<string, any>>(sourceObj: T): T {
    const objectIterator = (input: any): any => {
        if (Array.isArray(input)) {
            return input.map((item) => objectIterator(item));
        }
        if (isRef(input) || isReactive(input) || isProxy(input)) {
            return objectIterator(toRaw(input));
        }
        if (input && typeof input === 'object' && Object.keys(input).length > 0) {
// This one
            return Object.keys(input).reduce((acc, key) => {
                acc[key as keyof typeof acc] = objectIterator(input[key]);
                return acc;
            }, {} as T);
        }
        return input;
    };

    return objectIterator(sourceObj);
}
```

**Comment by treardon17** [comment]
This is a similar issue to what I'm facing, although the objects I'm passing in happen to be classes that have circular references, so this function does a few things that break my use case:

1. Returns raw objects instead of the class instances
2. Calls every getter on every class instance
3. Recurses infinitely until the app crashes

**Comment by sabahang** [comment]
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-13735**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/

Thanks again for bringing this up with us - we appreciate your time!

Kind regards,

**Comment by smakinson** [comment]
@sabahang 

I am in the process of upgrading to v33.0.3 and I ran into the `RangeError: Maximum call stack size exceeded` error. I am also using class instances for the data, but I happen to have a `ref` in a property and in the line with `objectIterator(toRaw(input))`, the `toRaw()` call returns a `ref`, so the recursion is infinite. I did some testing in devtools with the file override feature. I took the minified version of `deepToRaw` and had the jetbrains AI make it readable for me. I did a bit of console logging there. Then to save some time I chatted the AI, indicated the issue and asked for a fix in the function. I pasted this refactor of the function in the overridden file in devtools and I no longer get the `RangeError` when it is used. In case it's useful, here is the change in the original function from the `ag-grid-vue3` package. It uses a `WeakMap` to avoid the infinite recursion. I see that AG-13735 is marked as Scheduled. Let me know if I should open a new issue. 

```
export function deepToRaw<T extends Record<string, any>>(sourceObj: T): T {
  const seen = new WeakSet(); // To track visited objects and reactive values

  const objectIterator = (input: any): any => {
    if (Array.isArray(input)) {
      // Recursively process array elements
      return input.map((item) => objectIterator(item));
    }

    if (isRef(input) || isReactive(input) || isProxy(input)) {
      const rawValue = toRaw(input); // Get the raw value from reactive or ref objects

      if (seen.has(rawValue)) {
        return rawValue; // Avoid processing the same raw value again
      }

      seen.add(rawValue); // Mark this raw value as visited
      return objectIterator(rawValue); // Recursively process the raw value
    }

    if (input && typeof input === 'object' && Object.keys(input).length > 0) {
      if (seen.has(input)) {
        return input; // Avoid re-processing objects that have already been visited
      }

      seen.add(input); // Mark the object as visited

      return Object.keys(input).reduce((acc, key) => {
        // Avoid converting classes to "raw" objects
        acc[key as keyof typeof acc] = isInputClass(input[key]) ? input[key] : objectIterator(input[key]);
        return acc;
      }, {} as T);
    }

    return input; // Base case: if the value is neither array nor object, return it as is
  };

  return objectIterator(sourceObj);
}
```

**Comment by sabahang** [comment]
@smakinson yes this issue is scheduled and the fix will be out with our next release.

**Comment by treardon17** [comment]
@sabahang This issue was marked as "done" in version [33.0.4](https://www.ag-grid.com/changelog?fixVersion=33.0.4) but is still a problem for me. The `deepToRaw` function doesn't seem to infinitely recurse any longer (in my case) but it still converts class instances to regular objects. This breaks how my application handles row selections (strict equality checks between objects), and also removes all of the getters from my class instance so the data shown in the table (via custom table cells/cellRenderer) are stale.

It appears that `deepToRaw` is used to "Prevent the grids internal edits from being reactive" but edits are not relevant to my use case. Can `deepToRaw` at least be made optional through configuration? I need the data passed to the table to be the same data that comes out of the table.

**Comment by sabahang** [comment]
@treardon17 we think the original issue should be resolved. However if you think this is not the case could you please provide a repo live example that demonstrates the issue? This way we can look into it

**Comment by treardon17** [comment]
@sabahang I submitted another ticket and it's been put on the backlog: https://github.com/ag-grid/ag-grid/issues/9891

Currently marked as a feature request, but it's a regression from version 32.3.3.
